# Generated by Django 4.1.1 on 2022-12-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_remove_userdetails_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='address',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='phone_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
