# Generated by Django 4.1.1 on 2022-12-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0005_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item_img',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantitie',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
