# Generated by Django 4.1.1 on 2022-12-18 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0006_remove_cart_brand_name_remove_cart_item_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20)),
                ('message', models.TextField(default=None)),
                ('date', models.DateField(default=None)),
                ('time', models.TimeField(default=None)),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='msg', to='cart_app.item')),
            ],
        ),
    ]
