# Generated by Django 4.1.1 on 2022-12-25 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0011_alter_cart_item_name_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemquantite',
            name='price',
        ),
    ]
