# Generated by Django 4.1.1 on 2022-12-25 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0012_remove_itemquantite_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemquantite',
            name='item',
        ),
    ]
