# Generated by Django 4.1.1 on 2023-01-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0013_remove_itemquantite_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionans',
            name='date',
        ),
        migrations.RemoveField(
            model_name='questionans',
            name='time',
        ),
        migrations.RemoveField(
            model_name='questionans',
            name='user',
        ),
        migrations.AddField(
            model_name='questionans',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
