# Generated by Django 4.1.1 on 2023-01-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0014_remove_questionans_date_remove_questionans_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionans',
            name='question',
            field=models.TextField(default=None),
        ),
    ]
