# Generated by Django 4.1.1 on 2023-01-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0016_alter_questionans_answer_alter_questionans_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionans',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
