# Generated by Django 4.1.1 on 2023-01-22 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0018_alter_questionans_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionans',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='questionans',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_product', to='cart_app.item'),
        ),
    ]
